# Generated by Django 2.2.4 on 2023-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
