# Generated by Django 2.2.4 on 2023-06-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
